//
package sistemaescuela;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;
// FATIMA AIDA LEON REBOLLO
public class FrmAgregarDocente extends javax.swing.JFrame {

    /**
     * Creates new form FrmAgregarDocente
     */
    public FrmAgregarDocente() {
        initComponents();
        setLocationRelativeTo(this);
        txtIdentificacion.setText(GestionEscuela.listaDocentes.size()+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnColor = new javax.swing.JPanel();
        lbAggDocente = new javax.swing.JLabel();
        txtIdentificacion = new javax.swing.JTextField();
        lbIdentificacion = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        lbCorreo = new javax.swing.JLabel();
        lbPreofesion = new javax.swing.JLabel();
        cbProfesion = new javax.swing.JComboBox<>();
        btnAgregarDocente = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnColor.setBackground(new java.awt.Color(153, 153, 255));

        lbAggDocente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbAggDocente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbAggDocente.setText("AGREGAR DOCENTES");

        javax.swing.GroupLayout pnColorLayout = new javax.swing.GroupLayout(pnColor);
        pnColor.setLayout(pnColorLayout);
        pnColorLayout.setHorizontalGroup(
            pnColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnColorLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbAggDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        pnColorLayout.setVerticalGroup(
            pnColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnColorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbAggDocente)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        txtIdentificacion.setEditable(false);
        txtIdentificacion.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtIdentificacion.setForeground(new java.awt.Color(153, 153, 255));

        lbIdentificacion.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbIdentificacion.setText("Identificación:");

        lbNombre.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbNombre.setText("Nombre:");

        txtNombre.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(153, 153, 255));

        txtCorreo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(153, 153, 255));

        lbCorreo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbCorreo.setText("Correo:");

        lbPreofesion.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbPreofesion.setText("Profesión:");

        cbProfesion.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbProfesion.setForeground(new java.awt.Color(153, 153, 255));
        cbProfesion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingeniero de Sistemas", "Ingeniero Industrial", "Ingeniero en Hardware", " " }));
        cbProfesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProfesionActionPerformed(evt);
            }
        });

        btnAgregarDocente.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAgregarDocente.setForeground(new java.awt.Color(153, 153, 255));
        btnAgregarDocente.setText("AGRREGAR");
        btnAgregarDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarDocenteActionPerformed(evt);
            }
        });

        btnRegresar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(153, 153, 255));
        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCorreo)
                            .addComponent(cbProfesion, 0, 212, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbIdentificacion)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbCorreo)
                                .addComponent(lbNombre))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbPreofesion)
                                .addGap(5, 5, 5)))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdentificacion, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addComponent(txtNombre)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnAgregarDocente)
                        .addGap(25, 25, 25)
                        .addComponent(btnRegresar)))
                .addContainerGap(46, Short.MAX_VALUE))
            .addComponent(pnColor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIdentificacion)
                    .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCorreo)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPreofesion)
                    .addComponent(cbProfesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregarDocente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Método qye agrega un docente a la lista de docentes
    private void btnAgregarDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarDocenteActionPerformed
        // TODO add your handling code here:
        if (!txtIdentificacion.getText().isEmpty() && !txtCorreo.getText().isEmpty()
            && !txtNombre.getText().isEmpty()){

            try{
                int identifica = Integer.parseInt(txtIdentificacion.getText());
                String nombre = txtNombre.getText();
                String correo = txtCorreo.getText();
                String profesion = cbProfesion.getSelectedItem().toString();
                Docente unDocente = new Docente(profesion, txtIdentificacion.getText(), nombre, correo);
                if (GestionEscuela.existeDocente(txtIdentificacion.getText())==false){
                    GestionEscuela.agregarDocente(unDocente);
                    JOptionPane.showMessageDialog(null, "Docente Agregado Correctamente");
                    txtCorreo.setText("");
                    txtNombre.setText("");
                    txtIdentificacion.setText(GestionEscuela.listaDocentes.size()+"");
                }else{
                    JOptionPane.showMessageDialog(null, "Ya existe docente con esa identificación");
                }
            }catch (NumberFormatException | HeadlessException ex){
                JOptionPane.showMessageDialog(null, "Problemas al agregar " + ex.getMessage());
            }

        }else{
            JOptionPane.showMessageDialog(null, "Faltan Datos, Revisar.....");
        }
    }//GEN-LAST:event_btnAgregarDocenteActionPerformed

    //BOTON REGRESAR
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void cbProfesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProfesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbProfesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAgregarDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAgregarDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAgregarDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAgregarDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAgregarDocente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarDocente;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cbProfesion;
    private javax.swing.JLabel lbAggDocente;
    private javax.swing.JLabel lbCorreo;
    private javax.swing.JLabel lbIdentificacion;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbPreofesion;
    private javax.swing.JPanel pnColor;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
